apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  {{- if .values.knativeServing.config }}
  {{- toYaml .values.knativeServing.config | nindent 2 }}
  {{- end }}